# Generated by Django 3.0.3 on 2020-02-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coyname', models.CharField(max_length=30)),
                ('countryname', models.CharField(max_length=30)),
                ('countrystatus', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('featurereport', models.IntegerField()),
                ('goldcommunity', models.IntegerField()),
                ('companylisted', models.IntegerField()),
                ('organisationtype', models.IntegerField()),
                ('sector', models.IntegerField()),
                ('companysize', models.IntegerField()),
            ],
        ),
    ]
