# Generated by Django 3.0.3 on 2020-02-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='approvals',
            new_name='RequestForm',
        ),
    ]
