# Generated by Django 3.0.3 on 2020-02-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crAPI', '0002_auto_20200229_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='countrystatus',
            field=models.IntegerField(),
        ),
    ]
