# Generated by Django 3.0.3 on 2020-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crAPI', '0003_auto_20200229_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='companylisted',
            field=models.IntegerField(choices=[('Listed', 'Listed'), ('Non-listed', 'Non-listed'), ('nan', 'nan'), ('Not applicable', 'Not applicable')]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='companysize',
            field=models.IntegerField(choices=[('Large', 'Large'), ('MNE', 'MNE'), ('SME', 'SME'), ('nan', 'nan')]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='countrystatus',
            field=models.IntegerField(choices=[('OECD', 'OECD'), ('DAC-UMICT', 'DAC-UMICT'), ('Non-OECD / Non-DAC', 'Non-OECD / Non-DAC'), ('DAC-LMICT', 'DAC-LMICT'), ('DAC-LDC', 'DAC-LDC'), ('DAC-OLIC', 'DAC-OLIC')]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='featurereport',
            field=models.IntegerField(choices=[('No', 'No'), ('nan', 'nan'), ('Yes', 'Yes')]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='goldcommunity',
            field=models.IntegerField(choices=[('No', 'No'), ('nan', 'nan'), ('Yes', 'Yes')]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='organisationtype',
            field=models.IntegerField(choices=[('Private company', 'Private company'), ('Subsidiary', 'Subsidiary'), ('nan', 'nan'), ('State-owned company', 'State-owned company'), ('Cooperative', 'Cooperative'), ('Non-profit organization', 'Non-profit organization'), ('Public institution', 'Public institution'), ('Partnership', 'Partnership')]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='sector',
            field=models.IntegerField(choices=[('No', 'Energy Utilities'), ('nan', 'Healthcare Products'), ('Yes', 'Aviation'), ('No', 'Consumer Durables'), ('Construction Materials', 'Construction Materials'), ('Automotive', 'Automotive'), ('Household and Personal Products', 'Household and Personal Products'), ('Energy', 'Energy'), ('Forest and Paper Products', 'Forest and Paper Products'), ('Conglomerates', 'Conglomerates'), ('Financial Services', 'Financial Services'), ('Waste Management', 'Waste Management'), ('Construction', 'Construction'), ('Mining', 'Mining'), ('Technology Hardware', 'Technology Hardware'), ('Other', 'Other'), ('Equipment', 'Equipment'), ('Metals Products', 'Metals Products'), ('Food and Beverage Products', 'Food and Beverage Products'), ('Telecommunications', 'Telecommunications'), ('Media', 'Media'), ('Tourism/Leisure', 'Tourism/Leisure'), ('Real Estate', 'Real Estate'), ('Tobacco', 'Tobacco'), ('Water Utilities', 'Water Utilities'), ('Healthcare Services', 'Healthcare Services'), ('Retailers', 'Retailers'), ('Non-Profit / Services', 'Non-Profit / Services'), ('Railroad', 'Railroad'), ('Commercial Services', 'Commercial Services'), ('Textiles and Apparel', 'Textiles and Apparel'), ('Universities', 'Universities'), ('Computers', 'Computers'), ('Logistics', 'Logistics'), ('Agriculture', 'Agriculture'), ('Public Agency', 'Public Agency'), ('Toys', 'Toys'), ('=', '=')]),
        ),
    ]
